### ISSUE TITLE
gedis actors_list returns wrong values

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/digitalmeX#250]
![image](https://user-images.githubusercontent.com/17981089/57019272-4beea980-6c26-11e9-8915-b3fc1be43a47.png)

code:
```python
server = j.servers.gedis.configure(name='test', port=8889, host='0.0.0.0', ssl=False, password='')
server.actor_add('/tmp/actor.py', namespace='demo')
server.actors_list(namespace='demo')
```

**branch**
dev

**Comment by despiegk** [comment]
relevant on latest branch?

**Comment by waleedhammam** [comment]
on branch **development_jumpscale**
fix: https://github.com/threefoldtech/digitalmeX/commit/1359304605b0727d8f0417091c7f2af4eaef7558
due to new changes you can't get a client if it's not created first, now working OK
`server = j.servers.gedis.new(name='test', port=8889, host='0.0.0.0', ssl=False, password='')`

**Comment by Dinaamagdy** [comment]
list_actors should return actors inside namespace demo not namespace itself

**Comment by waleedhammam** [comment]
fix: https://github.com/threefoldtech/digitalmeX/commit/bf20050082722d385cc9f0320d1ac902264d4be1 return list of actor names
```
server = j.servers.gedis.new(name='test', port=8889, host='0.0.0.0', ssl=False, password='') 
server.actor_add('/tmp/actor.py', namespace='demo') 
server.actors_list(namespace='demo') 
```
returns
```
['demo__actor']
```

**Comment by Dinaamagdy** [comment]
verified on development  jumpscale
